
package com.emulator.domain.soap.com.bssys.sbns.upg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UniversalPaymentGate", targetNamespace = "http://upg.sbns.bssys.com/", wsdlLocation = "file:/C:/Users/petrov_dv/eclipse-workspace/QueryEmulator/src/main/java/com/emulator/domain/wsclient/upg_new.xml")
public class UniversalPaymentGate_Service
    extends Service
{

    private final static URL UNIVERSALPAYMENTGATE_WSDL_LOCATION;
    private final static WebServiceException UNIVERSALPAYMENTGATE_EXCEPTION;
    private final static QName UNIVERSALPAYMENTGATE_QNAME = new QName("http://upg.sbns.bssys.com/", "UniversalPaymentGate");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/petrov_dv/eclipse-workspace/QueryEmulator/src/main/java/com/emulator/domain/wsclient/upg_new.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIVERSALPAYMENTGATE_WSDL_LOCATION = url;
        UNIVERSALPAYMENTGATE_EXCEPTION = e;
    }

    public UniversalPaymentGate_Service() {
        super(__getWsdlLocation(), UNIVERSALPAYMENTGATE_QNAME);
    }

    public UniversalPaymentGate_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIVERSALPAYMENTGATE_QNAME, features);
    }

    public UniversalPaymentGate_Service(URL wsdlLocation) {
        super(wsdlLocation, UNIVERSALPAYMENTGATE_QNAME);
    }

    public UniversalPaymentGate_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIVERSALPAYMENTGATE_QNAME, features);
    }

    public UniversalPaymentGate_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UniversalPaymentGate_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UniversalPaymentGate
     */
    @WebEndpoint(name = "UniversalPaymentGateImplPort")
    public UniversalPaymentGate getUniversalPaymentGateImplPort() {
        return super.getPort(new QName("http://upg.sbns.bssys.com/", "UniversalPaymentGateImplPort"), UniversalPaymentGate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UniversalPaymentGate
     */
    @WebEndpoint(name = "UniversalPaymentGateImplPort")
    public UniversalPaymentGate getUniversalPaymentGateImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://upg.sbns.bssys.com/", "UniversalPaymentGateImplPort"), UniversalPaymentGate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIVERSALPAYMENTGATE_EXCEPTION!= null) {
            throw UNIVERSALPAYMENTGATE_EXCEPTION;
        }
        return UNIVERSALPAYMENTGATE_WSDL_LOCATION;
    }

}
